from visions.typesets.typeset import VisionsTypeset

from visions.typesets.visions_complete_set import visions_complete_set
from visions.typesets.visions_standard_set import visions_standard_set
from visions.typesets.visions_geometry_set import visions_geometry_set
